// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Racunala.Data;

namespace Racunala.Migrations
{
    [DbContext(typeof(RacunalaContext))]
    partial class RacunalaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Racunala.Models.Racunalo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktivno")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("DanasAktivno")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumPustanjaUPromet")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lokacija")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Racunalo");
                });
#pragma warning restore 612, 618
        }
    }
}
